# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Writing Pad
email: weiqingtoh@gmail.com
description: >
  Random stuff I've tried to figure out and probably not want to forget.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://weiqingtoh.github.io" # the base hostname & protocol for your site
twitter_username: weiqingtoh
github_username:  weiqingtoh
timezone: Asia/Singapore

# Build settings
markdown: kramdown
